// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: analyzer.proto

package protoServices

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DomainAnalysisServiceClient is the client API for DomainAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DomainAnalysisServiceClient interface {
	GetFullScoring(ctx context.Context, in *FullDomainScoringParams, opts ...grpc.CallOption) (*DomainScoring, error)
}

type domainAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDomainAnalysisServiceClient(cc grpc.ClientConnInterface) DomainAnalysisServiceClient {
	return &domainAnalysisServiceClient{cc}
}

func (c *domainAnalysisServiceClient) GetFullScoring(ctx context.Context, in *FullDomainScoringParams, opts ...grpc.CallOption) (*DomainScoring, error) {
	out := new(DomainScoring)
	err := c.cc.Invoke(ctx, "/services.DomainAnalysisService/GetFullScoring", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DomainAnalysisServiceServer is the server API for DomainAnalysisService service.
// All implementations must embed UnimplementedDomainAnalysisServiceServer
// for forward compatibility
type DomainAnalysisServiceServer interface {
	GetFullScoring(context.Context, *FullDomainScoringParams) (*DomainScoring, error)
	mustEmbedUnimplementedDomainAnalysisServiceServer()
}

// UnimplementedDomainAnalysisServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDomainAnalysisServiceServer struct {
}

func (UnimplementedDomainAnalysisServiceServer) GetFullScoring(context.Context, *FullDomainScoringParams) (*DomainScoring, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullScoring not implemented")
}
func (UnimplementedDomainAnalysisServiceServer) mustEmbedUnimplementedDomainAnalysisServiceServer() {}

// UnsafeDomainAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DomainAnalysisServiceServer will
// result in compilation errors.
type UnsafeDomainAnalysisServiceServer interface {
	mustEmbedUnimplementedDomainAnalysisServiceServer()
}

func RegisterDomainAnalysisServiceServer(s grpc.ServiceRegistrar, srv DomainAnalysisServiceServer) {
	s.RegisterService(&DomainAnalysisService_ServiceDesc, srv)
}

func _DomainAnalysisService_GetFullScoring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullDomainScoringParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAnalysisServiceServer).GetFullScoring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DomainAnalysisService/GetFullScoring",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAnalysisServiceServer).GetFullScoring(ctx, req.(*FullDomainScoringParams))
	}
	return interceptor(ctx, in, info, handler)
}

// DomainAnalysisService_ServiceDesc is the grpc.ServiceDesc for DomainAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DomainAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.DomainAnalysisService",
	HandlerType: (*DomainAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullScoring",
			Handler:    _DomainAnalysisService_GetFullScoring_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analyzer.proto",
}
